"""AI tool / agent API provider registry.

These services are not LLM model providers.  They get their own category,
capability metadata and validation semantics so the main scorer does not
mistake a successful search/scrape/browser API call for an LLM model.
Only authorized credentials should be validated.
"""
from __future__ import annotations
import re

PLUGIN_PROVIDERS = {
    "firecrawl": {
        "name": "Firecrawl",
        "category": "ai_tool",
        "priority": 82,
        "capabilities": ["scrape", "crawl", "search", "extract", "browser"],
        "env_name": "FIRECRAWL_API_KEY",
        "patterns": [re.compile(r"\bfc-[A-Za-z0-9_-]{16,}\b")],
        "headers": lambda k: {"Authorization": f"Bearer {k}"},
        "validate": {"method": "GET", "url": "https://api.firecrawl.dev/v1/team/credit-usage", "ok": [200]},
        "detail": "generic", "has_balance": True,
    },
    "browser_use": {
        "name": "Browser Use",
        "category": "ai_tool",
        "priority": 84,
        "capabilities": ["browser", "agent", "sessions", "profiles", "cdp"],
        "env_name": "BROWSER_USE_API_KEY",
        "patterns": [re.compile(r"\bbu_[A-Za-z0-9_-]{20,}\b")],
        "headers": lambda k: {"X-Browser-Use-API-Key": k},
        "validate": {"method": "GET", "url": "https://api.browser-use.com/api/v3/sessions", "ok": [200]},
        "detail": "generic", "has_balance": False,
    },
    "browserless": {
        "name": "Browserless",
        "category": "ai_tool",
        "priority": 80,
        "capabilities": ["browser", "scrape", "screenshot", "pdf", "content", "playwright"],
        "env_name": "BROWSERLESS_TOKEN",
        "patterns": [re.compile(r"\bbless_[A-Za-z0-9_-]{12,}\b")],
        "headers": lambda k: {},
        "validate": {"method": "GET", "url": "https://production-sfo.browserless.io/content?token={key}&url=https%3A%2F%2Fexample.com", "ok": [200], "key_in_url": True},
        "detail": "generic", "has_balance": False,
    },
    "apify": {
        "name": "Apify",
        "category": "ai_tool",
        "priority": 79,
        "capabilities": ["actors", "scraping", "automation", "datasets", "proxy"],
        "env_name": "APIFY_API_TOKEN",
        "patterns": [re.compile(r"\bapify_api_[A-Za-z0-9_-]{20,}\b")],
        "headers": lambda k: {"Authorization": f"Bearer {k}"},
        "validate": {"method": "GET", "url": "https://api.apify.com/v2/users/me", "ok": [200]},
        "detail": "generic", "has_balance": True,
    },
    "serper": {
        "name": "Serper",
        "category": "ai_tool",
        "priority": 76,
        "capabilities": ["google_search", "news", "images", "places"],
        "env_name": "SERPER_API_KEY",
        "patterns": [],
        "headers": lambda k: {"X-API-KEY": k, "Content-Type": "application/json"},
        "validate": {"method": "POST", "url": "https://google.serper.dev/search", "ok": [200],
                     "json": {"q": "example.com", "num": 1}},
        "detail": "generic", "has_balance": False, "weak_pattern": True,
    },
    "exa": {
        "name": "Exa",
        "category": "ai_tool",
        "priority": 78,
        "capabilities": ["neural_search", "web_search", "contents", "research"],
        "env_name": "EXA_API_KEY",
        "patterns": [re.compile(r"\bexa_[A-Za-z0-9_-]{16,}\b")],
        "headers": lambda k: {"x-api-key": k, "Content-Type": "application/json"},
        "validate": {"method": "POST", "url": "https://api.exa.ai/search", "ok": [200],
                     "json": {"query": "example.com", "numResults": 1}},
        "detail": "generic", "has_balance": False,
    },
    "scrapingbee": {
        "name": "ScrapingBee",
        "category": "ai_tool",
        "priority": 74,
        "capabilities": ["scrape", "javascript", "premium_proxy", "stealth"],
        "env_name": "SCRAPINGBEE_API_KEY",
        "patterns": [],
        "headers": lambda k: {},
        "validate": {"method": "GET", "url": "https://app.scrapingbee.com/api/v1/?api_key={key}&url=https%3A%2F%2Fexample.com", "ok": [200], "key_in_url": True},
        "detail": "generic", "has_balance": False, "weak_pattern": True,
    },
    "scraperapi": {
        "name": "ScraperAPI",
        "category": "ai_tool",
        "priority": 74,
        "capabilities": ["scrape", "javascript", "geolocation", "proxy"],
        "env_name": "SCRAPERAPI_API_KEY",
        "patterns": [],
        "headers": lambda k: {},
        "validate": {"method": "GET", "url": "https://api.scraperapi.com/account?api_key={key}", "ok": [200], "key_in_url": True},
        "detail": "generic", "has_balance": True, "weak_pattern": True,
    },
    "brightdata": {
        "name": "Bright Data",
        "category": "ai_tool",
        "priority": 73,
        "capabilities": ["web_unlocker", "scraping", "browser", "proxy", "serp"],
        "env_name": "BRIGHTDATA_API_KEY",
        "patterns": [re.compile(r"\bbrd_[A-Za-z0-9_-]{16,}\b")],
        "headers": lambda k: {"Authorization": f"Bearer {k}"},
        "validate": {"method": "GET", "url": "https://api.brightdata.com/zone", "ok": [200]},
        "detail": "generic", "has_balance": False,
    },
    "deepgram": {
        "name": "Deepgram",
        "category": "ai_tool",
        "priority": 81,
        "capabilities": ["speech_to_text", "text_to_speech", "voice_agent", "text_intelligence"],
        "env_name": "DEEPGRAM_API_KEY",
        "patterns": [],
        "headers": lambda k: {"Authorization": f"Token {k}"},
        "validate": {"method": "GET", "url": "https://api.deepgram.com/v1/projects", "ok": [200]},
        "detail": "generic", "has_balance": False, "weak_pattern": True,
    },
    "assemblyai": {
        "name": "AssemblyAI",
        "category": "ai_tool",
        "priority": 80,
        "capabilities": ["speech_to_text", "summarization", "speaker_diarization", "audio_intelligence"],
        "env_name": "ASSEMBLYAI_API_KEY",
        "patterns": [],
        "headers": lambda k: {"Authorization": k},
        "validate": {"method": "GET", "url": "https://api.assemblyai.com/v2/account", "ok": [200]},
        "detail": "generic", "has_balance": True, "weak_pattern": True,
    },
    "pinecone": {
        "name": "Pinecone",
        "category": "ai_tool",
        "priority": 77,
        "capabilities": ["vector_db", "embeddings", "rerank", "inference"],
        "env_name": "PINECONE_API_KEY",
        "patterns": [re.compile(r"\bpcsk_[A-Za-z0-9_-]{16,}\b")],
        "headers": lambda k: {"Api-Key": k, "Accept": "application/json"},
        "validate": {"method": "GET", "url": "https://api.pinecone.io/indexes", "ok": [200]},
        "detail": "generic", "has_balance": False,
    },
    "fal": {
        "name": "fal.ai",
        "category": "ai_tool",
        "priority": 76,
        "capabilities": ["image_generation", "video", "audio", "vision"],
        "env_name": "FAL_KEY",
        "patterns": [re.compile(r"\bfal_[A-Za-z0-9_-]{16,}\b")],
        "headers": lambda k: {"Authorization": f"Key {k}"},
        "validate": {"method": "GET", "url": "https://api.fal.ai/v1/models", "ok": [200]},
        "detail": "generic", "has_balance": False,
    },
    "unstructured": {
        "name": "Unstructured",
        "category": "ai_tool",
        "priority": 72,
        "capabilities": ["document_parsing", "ocr", "partition", "connectors", "workflows"],
        "env_name": "UNSTRUCTURED_API_KEY",
        "patterns": [],
        "headers": lambda k: {"unstructured-api-key": k, "Accept": "application/json"},
        "validate": {"method": "GET", "url": "https://api.unstructuredapp.io/api/v1/sources", "ok": [200]},
        "detail": "generic", "has_balance": False, "weak_pattern": True,
    },
    "modal": {
        "name": "Modal",
        "category": "ai_tool",
        "priority": 71,
        "capabilities": ["serverless", "gpu", "jobs", "web_endpoints"],
        "env_name": "MODAL_TOKEN_ID",
        "patterns": [re.compile(r"\bak-[A-Za-z0-9_-]{12,}\b")],
        "headers": lambda k: {},
        "validate": {"method": "GET", "url": "https://api.modal.com/v1/users/me", "ok": [200]},
        "detail": "generic", "has_balance": False, "weak_pattern": True,
        "credential_pair": "MODAL_TOKEN_SECRET",
    },
}

for _pid, _cfg in PLUGIN_PROVIDERS.items():
    _cfg["provider_kind"] = "tool"
